### ISSUE TITLE
Bug: Recipe 12 IE11 broken with Next.js 11.1

### ISSUE THREAD

**Issue by pgrippi** [ezcater/recipe#695]
## Describe the bug

First discovered in store-next

Something about next.js 11.1.X breaks recipe 12 in IE11. I tracked it down to the compiled `dist/esm/components/theme.config.js` - specifically the return statement in `mergeCss`:

```js
  return _objectSpread(_objectSpread({}, stitches), {}, {
    css: css
  });
```

When this is executed IE11 blows up, saying that it cannot iterate over a non-iterable object.

```
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
  at m (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:777893)
  at K (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:792108)
  at Q (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:790074)
  at Anonymous function (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:789277)
  at css (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:805038)
  at Anonymous function (https://static.cdn-ezcater.com/store-next/_next/static/chunks/pages/_app-1642d05ad448af6c0d53.js:1:807091)
  at n (https://static.cdn-ezcater.com/store-next/_next/static/chunks/webpack-d9fb22640d4ee5be6114.js:1:144)
```

This error happens in the `_app` component, which prevents next from booting and ends up showing a blank white page to IE11 users. This is blocking us from upgrading next to address a CVE.

## Steps To Reproduce

1. Add recipe to a next.js 11.1.X app and load the page in IE11

**Comment by pgrippi** [comment]
Closed as recipe no longer supports IE11 and neither does the marketplace, so there is no need to fix this!
